rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx
script: 
  - "sudo aptitude -y -q install lame"
  - "sh -c 'cd test/dummy && bundle exec rake db:create db:migrate db:test:prepare'"
  - "bundle exec rake test"